import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import dynamic from 'next/dynamic'
 
//Gloabl Common
const NavigationBar = dynamic(() => import('@/common/nav'), { ssr: false })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Algo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head></head>
      <NavigationBar/>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
